--- !TrainingConfig
# Training
epoch: 2
batch_size: 128

# vector-space embedding
n_dim: 64
n_unique_words: 5000       
n_words_to_skip: 50        
max_review_length: 400
pad_type: "pre"
trunc_type: "pre"          
drop_embed: 0.2

# compile
optimizer: "adam"
loss: "binary_crossentropy"
metrics: ["accuracy"]
